# Generated by Django 5.2.3 on 2025-07-02 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(22)])),
            ],
        ),
        migrations.CreateModel(
            name='HitSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(22)])),
            ],
        ),
    ]
