# Generated by Django 5.2.3 on 2025-07-02 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_currenthit_delete_hitsubmissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(22)])),
                ('track_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HitSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(22)])),
                ('track_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
    ]
